export const CardDescriptionData = [
    {
        id: 1,
        img: "https://i.imgur.com/kBMN3Np.png",
        title: "Top 4 Die Hard Succulents Pack",
        price: 699,
        b1: "You get 4 succulent plants + 4 Colorful Pots in a single pack.", 
        b2: "Plants in this pack are easy to care for and require low maintenance.", 
        b3: "Succulent plants are hard to kill and impart beauty to your garden.", 
        b4: "A perfect pack to start growing plants worry-free.",
    },
    {
        id: 2,
        img: "https://i.imgur.com/ySZw3pv.png",
        title: "5 Best Indoor Plants Pack",
        price: 1149,
        b1: "You get different 5 houseplants in the single pack",
        b2: "Plants in this pack are easy to care.", 
        b3: "These are the best plants for improving air quality and controlling the inside temperature.", 
        b4: "Surround your home with these best pollution killer plants for a clean and healthy environment.",
    },
    {
        id: 3,
        img: "https://i.imgur.com/4mO83qB.png",
        title: "5 Best Fragrant Plants",
        price: 1599,
        b1: "You plant a hope when you bring Fragrant Plants at your Home.", 
        b2: "You hope that it grows a happy life and brings in luck and kindness & Frgrance in your household.", 
        b3: "These Plants play a very important role as they energize our surroundings.", 
        b4: "These plants have a pleasant scent.These plants have a pleasant scent.",
    },
    {
        id: 4,
        img: "https://i.imgur.com/ht8BbTh.png",
        title: "Top 5 air purifier and oxygen enriching plant pack",
        price: 1299,
        b1: "Reducing carbon dioxide levels", 
        b2: "Reducing levels of certain pollutants, such as benzene and nitrogen dioxide", 
        b3: "Plants have long been used to reduce noise from busy road", 
        b4: "Plants are incredibly beneficial to indoor work spaces,they also have air purifying qualities",
    },
    {
        id: 5,
        img: "https://i.imgur.com/yqiJmV2.png",
        title: "Plant Pack For Healthy Home-Office",
        price: 949,
        b1: "Plants in this pack are very easy to care and require low maintenance.", 
        b2: "All plants in this pack are NASA recommended air purifier plants.", 
        b3: "Plant in this pack Best for AC rooms, office desk, Home.", 
        b4: "Plant in this pack Best indoor plant for low light conditions.",
    },
    {
        id: 6,
        img: "https://i.imgur.com/enOnbaz.png",
        title: "Pack of 3 Good Luck Jade Plants in Ceramic Pots",
        price: 699,
        b1: "Plant in this pack is the perfect addition to sunny location in your home.", 
        b2: "Plants in this pack are easy to care and require low maintenance.", 
        b3: "Plants in this pack are believed to bring good luck and prosperity.", 
        b4: "You will get 3 Jade plants potted in a beautiful ceramic pot in a single pack.",
    },
    {
        id: 7,
        img: "https://i.imgur.com/1fMGvus.png",
        title: "Set of 3 Outdoor Flowering Plants for Beautiful Garden",
        price: 999,
        b1: "3 beautiful flowers along with blue color plastic pot and plate with decorative pebbles.", 
        b2: "These flowers will increase the ornamental look of your house.", 
        b3: "Plant in this pack are known for their elegant beauty and fragrant flowers", 
        b4: "Plants in this pack are very easy to grow and care.",
    },
    {
        id: 8,
        img: "https://i.imgur.com/D1kCTyG.png",
        title: "Top 5 Pollution Killer Plants Pack",
        price: 1149,
        b1: "You get 5 beautiful air purifier plants potted in colorful pots in a single pack.", 
        b2: "Plants in this pack are very easy to care and require low maintenance.", 
        b3: "These plants come in NASA air purifier list.", 
        b4: "Plants in this pack can be placed indoors on a location that receives indirect bright light.",
    },
]